/*
 * Created on 24 Oct 2015 ( Time 23:20:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.Book;
import com.kumasi.journal.domain.jpa.BookEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BookServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BookServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BookEntity' to 'Book'
	 * @param bookEntity
	 */
	public Book mapBookEntityToBook(BookEntity bookEntity) {
		if(bookEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Book book = map(bookEntity, Book.class);

		return book;
	}
	
	/**
	 * Mapping from 'Book' to 'BookEntity'
	 * @param book
	 * @param bookEntity
	 */
	public void mapBookToBookEntity(Book book, BookEntity bookEntity) {
		if(book == null) {
			return;
		}

		//--- Generic mapping 
		map(book, bookEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}