/*
 * Created on 24 Oct 2015 ( Time 23:20:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.BookCategory;
import com.kumasi.journal.domain.jpa.BookCategoryEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BookCategoryServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BookCategoryServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BookCategoryEntity' to 'BookCategory'
	 * @param bookCategoryEntity
	 */
	public BookCategory mapBookCategoryEntityToBookCategory(BookCategoryEntity bookCategoryEntity) {
		if(bookCategoryEntity == null) {
			return null;
		}

		//--- Generic mapping 
		BookCategory bookCategory = map(bookCategoryEntity, BookCategory.class);

		return bookCategory;
	}
	
	/**
	 * Mapping from 'BookCategory' to 'BookCategoryEntity'
	 * @param bookCategory
	 * @param bookCategoryEntity
	 */
	public void mapBookCategoryToBookCategoryEntity(BookCategory bookCategory, BookCategoryEntity bookCategoryEntity) {
		if(bookCategory == null) {
			return;
		}

		//--- Generic mapping 
		map(bookCategory, bookCategoryEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}