/*
 * Created on 24 Oct 2015 ( Time 23:20:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.Publisher;
import com.kumasi.journal.domain.jpa.PublisherEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PublisherServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PublisherServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PublisherEntity' to 'Publisher'
	 * @param publisherEntity
	 */
	public Publisher mapPublisherEntityToPublisher(PublisherEntity publisherEntity) {
		if(publisherEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Publisher publisher = map(publisherEntity, Publisher.class);

		return publisher;
	}
	
	/**
	 * Mapping from 'Publisher' to 'PublisherEntity'
	 * @param publisher
	 * @param publisherEntity
	 */
	public void mapPublisherToPublisherEntity(Publisher publisher, PublisherEntity publisherEntity) {
		if(publisher == null) {
			return;
		}

		//--- Generic mapping 
		map(publisher, publisherEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}