/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.journal.domain.jpa.CategoryEntity;
import com.kumasi.journal.persistence.commons.fake.GenericFakeService;
import com.kumasi.journal.persistence.services.CategoryPersistence;

/**
 * Fake persistence service implementation ( entity "Category" )
 *
 * @author Telosys Tools Generator
 */
public class CategoryPersistenceFAKE extends GenericFakeService<CategoryEntity> implements CategoryPersistence {

	public CategoryPersistenceFAKE () {
		super(CategoryEntity.class);
	}
	
	protected CategoryEntity buildEntity(int index) {
		CategoryEntity entity = new CategoryEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(CategoryEntity entity) {
		log("delete ( CategoryEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(CategoryEntity entity) {
		log("insert ( CategoryEntity : " + entity + ")" ) ;
	}

	public CategoryEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<CategoryEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<CategoryEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<CategoryEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public CategoryEntity save(CategoryEntity entity) {
		log("insert ( CategoryEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<CategoryEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
