/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.journal.domain.jpa.EntryEntity;
import com.kumasi.journal.persistence.commons.fake.GenericFakeService;
import com.kumasi.journal.persistence.services.EntryPersistence;

/**
 * Fake persistence service implementation ( entity "Entry" )
 *
 * @author Telosys Tools Generator
 */
public class EntryPersistenceFAKE extends GenericFakeService<EntryEntity> implements EntryPersistence {

	public EntryPersistenceFAKE () {
		super(EntryEntity.class);
	}
	
	protected EntryEntity buildEntity(int index) {
		EntryEntity entity = new EntryEntity();
		// Init fields with mock values
		entity.setIdentry( nextInteger() ) ;
		entity.setTitle( nextString() ) ;
		entity.setStoryDefinition( nextString() ) ;
		entity.setSuccessFactory( nextString() ) ;
		entity.setDateCreated( nextDate() ) ;
		entity.setDateModified( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(EntryEntity entity) {
		log("delete ( EntryEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer identry ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(EntryEntity entity) {
		log("insert ( EntryEntity : " + entity + ")" ) ;
	}

	public EntryEntity load( Integer identry ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<EntryEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<EntryEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<EntryEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public EntryEntity save(EntryEntity entity) {
		log("insert ( EntryEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<EntryEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
