/*
 * Created on 24 Oct 2015 ( Time 23:20:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.journal.domain.jpa.PublisherEntity;
import com.kumasi.journal.persistence.commons.fake.GenericFakeService;
import com.kumasi.journal.persistence.services.PublisherPersistence;

/**
 * Fake persistence service implementation ( entity "Publisher" )
 *
 * @author Telosys Tools Generator
 */
public class PublisherPersistenceFAKE extends GenericFakeService<PublisherEntity> implements PublisherPersistence {

	public PublisherPersistenceFAKE () {
		super(PublisherEntity.class);
	}
	
	protected PublisherEntity buildEntity(int index) {
		PublisherEntity entity = new PublisherEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setName( nextString() ) ;
		entity.setUrl( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(PublisherEntity entity) {
		log("delete ( PublisherEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(PublisherEntity entity) {
		log("insert ( PublisherEntity : " + entity + ")" ) ;
	}

	public PublisherEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<PublisherEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<PublisherEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<PublisherEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public PublisherEntity save(PublisherEntity entity) {
		log("insert ( PublisherEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<PublisherEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
