/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.kumasi.journal.web.common.AbstractController;
import com.kumasi.journal.web.common.FormMode;
import com.kumasi.journal.web.common.Message;
import com.kumasi.journal.web.common.MessageType;

//--- Entities
import com.kumasi.journal.domain.BookCategory;

//--- Services 
import com.kumasi.journal.business.service.BookCategoryService;


/**
 * Spring MVC controller for 'BookCategory' management.
 */
@Controller
@RequestMapping("/bookCategory")
public class BookCategoryController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "bookCategory";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "bookCategory/form";
	private static final String JSP_LIST   = "bookCategory/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/bookCategory/create";
	private static final String SAVE_ACTION_UPDATE   = "/bookCategory/update";

	//--- Main entity service
	@Resource
    private BookCategoryService bookCategoryService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public BookCategoryController() {
		super(BookCategoryController.class, MAIN_ENTITY_NAME );
		log("BookCategoryController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param bookCategory
	 */
	private void populateModel(Model model, BookCategory bookCategory, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, bookCategory);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of BookCategory found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<BookCategory> list = bookCategoryService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new BookCategory
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		BookCategory bookCategory = new BookCategory();	
		populateModel( model, bookCategory, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing BookCategory
	 * @param model Spring MVC model
	 * @param bookId  primary key element
	 * @param categoryId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{bookId}/{categoryId}")
	public String formForUpdate(Model model, @PathVariable("bookId") Integer bookId, @PathVariable("categoryId") Integer categoryId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		BookCategory bookCategory = bookCategoryService.findById(bookId, categoryId);
		populateModel( model, bookCategory, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bookCategory  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid BookCategory bookCategory, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				BookCategory bookCategoryCreated = bookCategoryService.create(bookCategory); 
				model.addAttribute(MAIN_ENTITY_NAME, bookCategoryCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, bookCategory.getBookId(), bookCategory.getCategoryId() );
			} else {
				populateModel( model, bookCategory, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "bookCategory.error.create", e);
			populateModel( model, bookCategory, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bookCategory  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid BookCategory bookCategory, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				BookCategory bookCategorySaved = bookCategoryService.update(bookCategory);
				model.addAttribute(MAIN_ENTITY_NAME, bookCategorySaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, bookCategory.getBookId(), bookCategory.getCategoryId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, bookCategory, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "bookCategory.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, bookCategory, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param bookId  primary key element
	 * @param categoryId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{bookId}/{categoryId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("bookId") Integer bookId, @PathVariable("categoryId") Integer categoryId) {
		log("Action 'delete'" );
		try {
			bookCategoryService.delete( bookId, categoryId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "bookCategory.error.delete", e);
		}
		return redirectToList();
	}

}
