/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.kumasi.journal.web.common.AbstractController;
import com.kumasi.journal.web.common.FormMode;
import com.kumasi.journal.web.common.Message;
import com.kumasi.journal.web.common.MessageType;

//--- Entities
import com.kumasi.journal.domain.Entry;
import com.kumasi.journal.domain.Entrytype;

//--- Services 
import com.kumasi.journal.business.service.EntryService;
import com.kumasi.journal.business.service.EntrytypeService;

//--- List Items 
import com.kumasi.journal.web.listitem.EntrytypeListItem;

/**
 * Spring MVC controller for 'Entry' management.
 */
@Controller
@RequestMapping("/entry")
public class EntryController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "entry";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "entry/form";
	private static final String JSP_LIST   = "entry/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/entry/create";
	private static final String SAVE_ACTION_UPDATE   = "/entry/update";

	//--- Main entity service
	@Resource
    private EntryService entryService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private EntrytypeService entrytypeService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public EntryController() {
		super(EntryController.class, MAIN_ENTITY_NAME );
		log("EntryController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Entrytype"
	 * @param model
	 */
	private void populateListOfEntrytypeItems(Model model) {
		List<Entrytype> list = entrytypeService.findAll();
		List<EntrytypeListItem> items = new LinkedList<EntrytypeListItem>();
		for ( Entrytype entrytype : list ) {
			items.add(new EntrytypeListItem( entrytype ) );
		}
		model.addAttribute("listOfEntrytypeItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param entry
	 */
	private void populateModel(Model model, Entry entry, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, entry);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfEntrytypeItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfEntrytypeItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Entry found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Entry> list = entryService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Entry
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Entry entry = new Entry();	
		populateModel( model, entry, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Entry
	 * @param model Spring MVC model
	 * @param identry  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{identry}")
	public String formForUpdate(Model model, @PathVariable("identry") Integer identry ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Entry entry = entryService.findById(identry);
		populateModel( model, entry, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param entry  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Entry entry, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Entry entryCreated = entryService.create(entry); 
				model.addAttribute(MAIN_ENTITY_NAME, entryCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, entry.getIdentry() );
			} else {
				populateModel( model, entry, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "entry.error.create", e);
			populateModel( model, entry, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param entry  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Entry entry, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Entry entrySaved = entryService.update(entry);
				model.addAttribute(MAIN_ENTITY_NAME, entrySaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, entry.getIdentry());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, entry, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "entry.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, entry, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param identry  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{identry}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("identry") Integer identry) {
		log("Action 'delete'" );
		try {
			entryService.delete( identry );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "entry.error.delete", e);
		}
		return redirectToList();
	}

}
