/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.domain.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "BookPublisherEntity" ( stored in table "Book_Publisher" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class BookPublisherEntityKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="Publisher_id", nullable=false)
    private Integer    publisherId  ;
    
    @Column(name="Book_id", nullable=false)
    private Integer    bookId       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public BookPublisherEntityKey() {
        super();
    }

    public BookPublisherEntityKey( Integer publisherId, Integer bookId ) {
        super();
        this.publisherId = publisherId ;
        this.bookId = bookId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setPublisherId( Integer value ) {
        this.publisherId = value;
    }
    public Integer getPublisherId() {
        return this.publisherId;
    }

    public void setBookId( Integer value ) {
        this.bookId = value;
    }
    public Integer getBookId() {
        return this.bookId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		BookPublisherEntityKey other = (BookPublisherEntityKey) obj; 
		//--- Attribute publisherId
		if ( publisherId == null ) { 
			if ( other.publisherId != null ) 
				return false ; 
		} else if ( ! publisherId.equals(other.publisherId) ) 
			return false ; 
		//--- Attribute bookId
		if ( bookId == null ) { 
			if ( other.bookId != null ) 
				return false ; 
		} else if ( ! bookId.equals(other.bookId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute publisherId
		result = prime * result + ((publisherId == null) ? 0 : publisherId.hashCode() ) ; 
		//--- Attribute bookId
		result = prime * result + ((bookId == null) ? 0 : bookId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(publisherId); 
		sb.append("|"); 
		sb.append(bookId); 
        return sb.toString();
    }
}
