/*
 * Created on 24 Oct 2015 ( Time 23:20:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.BookPublisher;
import com.kumasi.journal.domain.jpa.BookPublisherEntity;
import com.kumasi.journal.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class BookPublisherServiceMapperTest {

	private BookPublisherServiceMapper bookPublisherServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		bookPublisherServiceMapper = new BookPublisherServiceMapper();
		bookPublisherServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'BookPublisherEntity' to 'BookPublisher'
	 * @param bookPublisherEntity
	 */
	@Test
	public void testMapBookPublisherEntityToBookPublisher() {
		// Given
		BookPublisherEntity bookPublisherEntity = new BookPublisherEntity();
		
		// When
		BookPublisher bookPublisher = bookPublisherServiceMapper.mapBookPublisherEntityToBookPublisher(bookPublisherEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'BookPublisher' to 'BookPublisherEntity'
	 */
	@Test
	public void testMapBookPublisherToBookPublisherEntity() {
		// Given
		BookPublisher bookPublisher = new BookPublisher();

		BookPublisherEntity bookPublisherEntity = new BookPublisherEntity();
		
		// When
		bookPublisherServiceMapper.mapBookPublisherToBookPublisherEntity(bookPublisher, bookPublisherEntity);
		
		// Then
	}

}