/*
 * Created on 24 Oct 2015 ( Time 23:20:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.BookCategory;
import com.kumasi.journal.domain.jpa.BookCategoryEntity;
import com.kumasi.journal.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class BookCategoryServiceMapperTest {

	private BookCategoryServiceMapper bookCategoryServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		bookCategoryServiceMapper = new BookCategoryServiceMapper();
		bookCategoryServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'BookCategoryEntity' to 'BookCategory'
	 * @param bookCategoryEntity
	 */
	@Test
	public void testMapBookCategoryEntityToBookCategory() {
		// Given
		BookCategoryEntity bookCategoryEntity = new BookCategoryEntity();
		
		// When
		BookCategory bookCategory = bookCategoryServiceMapper.mapBookCategoryEntityToBookCategory(bookCategoryEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'BookCategory' to 'BookCategoryEntity'
	 */
	@Test
	public void testMapBookCategoryToBookCategoryEntity() {
		// Given
		BookCategory bookCategory = new BookCategory();

		BookCategoryEntity bookCategoryEntity = new BookCategoryEntity();
		
		// When
		bookCategoryServiceMapper.mapBookCategoryToBookCategoryEntity(bookCategory, bookCategoryEntity);
		
		// Then
	}

}