/*
 * Created on 24 Oct 2015 ( Time 23:20:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.Category;
import com.kumasi.journal.domain.jpa.CategoryEntity;
import com.kumasi.journal.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class CategoryServiceMapperTest {

	private CategoryServiceMapper categoryServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		categoryServiceMapper = new CategoryServiceMapper();
		categoryServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'CategoryEntity' to 'Category'
	 * @param categoryEntity
	 */
	@Test
	public void testMapCategoryEntityToCategory() {
		// Given
		CategoryEntity categoryEntity = new CategoryEntity();
		categoryEntity.setName(mockValues.nextString(150));
		
		// When
		Category category = categoryServiceMapper.mapCategoryEntityToCategory(categoryEntity);
		
		// Then
		assertEquals(categoryEntity.getName(), category.getName());
	}
	
	/**
	 * Test : Mapping from 'Category' to 'CategoryEntity'
	 */
	@Test
	public void testMapCategoryToCategoryEntity() {
		// Given
		Category category = new Category();
		category.setName(mockValues.nextString(150));

		CategoryEntity categoryEntity = new CategoryEntity();
		
		// When
		categoryServiceMapper.mapCategoryToCategoryEntity(category, categoryEntity);
		
		// Then
		assertEquals(category.getName(), categoryEntity.getName());
	}

}