/*
 * Created on 24 Oct 2015 ( Time 23:20:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.Entrytype;
import com.kumasi.journal.domain.jpa.EntrytypeEntity;
import com.kumasi.journal.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class EntrytypeServiceMapperTest {

	private EntrytypeServiceMapper entrytypeServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		entrytypeServiceMapper = new EntrytypeServiceMapper();
		entrytypeServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'EntrytypeEntity' to 'Entrytype'
	 * @param entrytypeEntity
	 */
	@Test
	public void testMapEntrytypeEntityToEntrytype() {
		// Given
		EntrytypeEntity entrytypeEntity = new EntrytypeEntity();
		entrytypeEntity.setDescription(mockValues.nextString(45));
		
		// When
		Entrytype entrytype = entrytypeServiceMapper.mapEntrytypeEntityToEntrytype(entrytypeEntity);
		
		// Then
		assertEquals(entrytypeEntity.getDescription(), entrytype.getDescription());
	}
	
	/**
	 * Test : Mapping from 'Entrytype' to 'EntrytypeEntity'
	 */
	@Test
	public void testMapEntrytypeToEntrytypeEntity() {
		// Given
		Entrytype entrytype = new Entrytype();
		entrytype.setDescription(mockValues.nextString(45));

		EntrytypeEntity entrytypeEntity = new EntrytypeEntity();
		
		// When
		entrytypeServiceMapper.mapEntrytypeToEntrytypeEntity(entrytype, entrytypeEntity);
		
		// Then
		assertEquals(entrytype.getDescription(), entrytypeEntity.getDescription());
	}

}