/*
 * Created on 24 Oct 2015 ( Time 23:20:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.Person;
import com.kumasi.journal.domain.jpa.PersonEntity;
import com.kumasi.journal.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class PersonServiceMapperTest {

	private PersonServiceMapper personServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		personServiceMapper = new PersonServiceMapper();
		personServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'PersonEntity' to 'Person'
	 * @param personEntity
	 */
	@Test
	public void testMapPersonEntityToPerson() {
		// Given
		PersonEntity personEntity = new PersonEntity();
		personEntity.setEmailAddress(mockValues.nextString(45));
		personEntity.setPassword(mockValues.nextString(45));
		personEntity.setFirstName(mockValues.nextString(45));
		personEntity.setLastName(mockValues.nextString(45));
		
		// When
		Person person = personServiceMapper.mapPersonEntityToPerson(personEntity);
		
		// Then
		assertEquals(personEntity.getEmailAddress(), person.getEmailAddress());
		assertEquals(personEntity.getPassword(), person.getPassword());
		assertEquals(personEntity.getFirstName(), person.getFirstName());
		assertEquals(personEntity.getLastName(), person.getLastName());
	}
	
	/**
	 * Test : Mapping from 'Person' to 'PersonEntity'
	 */
	@Test
	public void testMapPersonToPersonEntity() {
		// Given
		Person person = new Person();
		person.setEmailAddress(mockValues.nextString(45));
		person.setPassword(mockValues.nextString(45));
		person.setFirstName(mockValues.nextString(45));
		person.setLastName(mockValues.nextString(45));

		PersonEntity personEntity = new PersonEntity();
		
		// When
		personServiceMapper.mapPersonToPersonEntity(person, personEntity);
		
		// Then
		assertEquals(person.getEmailAddress(), personEntity.getEmailAddress());
		assertEquals(person.getPassword(), personEntity.getPassword());
		assertEquals(person.getFirstName(), personEntity.getFirstName());
		assertEquals(person.getLastName(), personEntity.getLastName());
	}

}