/*
 * Created on 24 Oct 2015 ( Time 23:20:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.journal.domain.Publisher;
import com.kumasi.journal.domain.jpa.PublisherEntity;
import com.kumasi.journal.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class PublisherServiceMapperTest {

	private PublisherServiceMapper publisherServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		publisherServiceMapper = new PublisherServiceMapper();
		publisherServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'PublisherEntity' to 'Publisher'
	 * @param publisherEntity
	 */
	@Test
	public void testMapPublisherEntityToPublisher() {
		// Given
		PublisherEntity publisherEntity = new PublisherEntity();
		publisherEntity.setName(mockValues.nextString(45));
		publisherEntity.setUrl(mockValues.nextString(75));
		
		// When
		Publisher publisher = publisherServiceMapper.mapPublisherEntityToPublisher(publisherEntity);
		
		// Then
		assertEquals(publisherEntity.getName(), publisher.getName());
		assertEquals(publisherEntity.getUrl(), publisher.getUrl());
	}
	
	/**
	 * Test : Mapping from 'Publisher' to 'PublisherEntity'
	 */
	@Test
	public void testMapPublisherToPublisherEntity() {
		// Given
		Publisher publisher = new Publisher();
		publisher.setName(mockValues.nextString(45));
		publisher.setUrl(mockValues.nextString(75));

		PublisherEntity publisherEntity = new PublisherEntity();
		
		// When
		publisherServiceMapper.mapPublisherToPublisherEntity(publisher, publisherEntity);
		
		// Then
		assertEquals(publisher.getName(), publisherEntity.getName());
		assertEquals(publisher.getUrl(), publisherEntity.getUrl());
	}

}