/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.test.persistence;


import com.kumasi.journal.domain.jpa.EntryEntity;
import com.kumasi.journal.mock.EntryEntityMock;
import com.kumasi.journal.persistence.PersistenceServiceProvider;
import com.kumasi.journal.persistence.services.EntryPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Entry persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class EntryPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		EntryPersistence service = PersistenceServiceProvider.getService(EntryPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Entry persistence : delete + load ..." );
		
		EntryPersistence service = PersistenceServiceProvider.getService(EntryPersistence.class);
		
		EntryEntityMock mock = new EntryEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(EntryPersistence service, EntryEntityMock mock, Integer identry ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		EntryEntity entity = service.load( identry );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( identry ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Entrytype
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( identry );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
