/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.kumasi.journal.domain.Category;
import com.kumasi.journal.business.service.CategoryService;
import com.kumasi.journal.web.listitem.CategoryListItem;

/**
 * Spring MVC controller for 'Category' management.
 */
@Controller
public class CategoryRestController {

	@Resource
	private CategoryService categoryService;
	
	@RequestMapping( value="/items/category",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<CategoryListItem> findAllAsListItems() {
		List<Category> list = categoryService.findAll();
		List<CategoryListItem> items = new LinkedList<CategoryListItem>();
		for ( Category category : list ) {
			items.add(new CategoryListItem( category ) );
		}
		return items;
	}
	
	@RequestMapping( value="/category",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Category> findAll() {
		return categoryService.findAll();
	}

	@RequestMapping( value="/category/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Category findOne(@PathVariable("id") Integer id) {
		return categoryService.findById(id);
	}
	
	@RequestMapping( value="/category",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Category create(@RequestBody Category category) {
		return categoryService.create(category);
	}

	@RequestMapping( value="/category/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Category update(@PathVariable("id") Integer id, @RequestBody Category category) {
		return categoryService.update(category);
	}

	@RequestMapping( value="/category/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		categoryService.delete(id);
	}
	
}
