/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.kumasi.journal.domain.Entrytype;
import com.kumasi.journal.business.service.EntrytypeService;
import com.kumasi.journal.web.listitem.EntrytypeListItem;

/**
 * Spring MVC controller for 'Entrytype' management.
 */
@Controller
public class EntrytypeRestController {

	@Resource
	private EntrytypeService entrytypeService;
	
	@RequestMapping( value="/items/entrytype",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<EntrytypeListItem> findAllAsListItems() {
		List<Entrytype> list = entrytypeService.findAll();
		List<EntrytypeListItem> items = new LinkedList<EntrytypeListItem>();
		for ( Entrytype entrytype : list ) {
			items.add(new EntrytypeListItem( entrytype ) );
		}
		return items;
	}
	
	@RequestMapping( value="/entrytype",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Entrytype> findAll() {
		return entrytypeService.findAll();
	}

	@RequestMapping( value="/entrytype/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Entrytype findOne(@PathVariable("id") Integer id) {
		return entrytypeService.findById(id);
	}
	
	@RequestMapping( value="/entrytype",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Entrytype create(@RequestBody Entrytype entrytype) {
		return entrytypeService.create(entrytype);
	}

	@RequestMapping( value="/entrytype/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Entrytype update(@PathVariable("id") Integer id, @RequestBody Entrytype entrytype) {
		return entrytypeService.update(entrytype);
	}

	@RequestMapping( value="/entrytype/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		entrytypeService.delete(id);
	}
	
}
