/*
 * Created on 24 Oct 2015 ( Time 23:23:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.kumasi.journal.domain.Publisher;
import com.kumasi.journal.business.service.PublisherService;
import com.kumasi.journal.web.listitem.PublisherListItem;

/**
 * Spring MVC controller for 'Publisher' management.
 */
@Controller
public class PublisherRestController {

	@Resource
	private PublisherService publisherService;
	
	@RequestMapping( value="/items/publisher",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<PublisherListItem> findAllAsListItems() {
		List<Publisher> list = publisherService.findAll();
		List<PublisherListItem> items = new LinkedList<PublisherListItem>();
		for ( Publisher publisher : list ) {
			items.add(new PublisherListItem( publisher ) );
		}
		return items;
	}
	
	@RequestMapping( value="/publisher",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Publisher> findAll() {
		return publisherService.findAll();
	}

	@RequestMapping( value="/publisher/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Publisher findOne(@PathVariable("id") Integer id) {
		return publisherService.findById(id);
	}
	
	@RequestMapping( value="/publisher",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Publisher create(@RequestBody Publisher publisher) {
		return publisherService.create(publisher);
	}

	@RequestMapping( value="/publisher/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Publisher update(@PathVariable("id") Integer id, @RequestBody Publisher publisher) {
		return publisherService.update(publisher);
	}

	@RequestMapping( value="/publisher/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		publisherService.delete(id);
	}
	
}
