/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.web.listitem;

import com.kumasi.journal.domain.BookPublisher;
import com.kumasi.journal.web.common.ListItem;

public class BookPublisherListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public BookPublisherListItem(BookPublisher bookPublisher) {
		super();

		this.value = ""
			 + bookPublisher.getPublisherId()
			 + "|"  + bookPublisher.getBookId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = bookPublisher.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
