/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.web.listitem;

import com.kumasi.journal.domain.Entrytype;
import com.kumasi.journal.web.common.ListItem;

public class EntrytypeListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public EntrytypeListItem(Entrytype entrytype) {
		super();

		this.value = ""
			 + entrytype.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = entrytype.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
