/*
 * Created on 24 Oct 2015 ( Time 23:23:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.web.listitem;

import com.kumasi.journal.domain.Publisher;
import com.kumasi.journal.web.common.ListItem;

public class PublisherListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PublisherListItem(Publisher publisher) {
		super();

		this.value = ""
			 + publisher.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = publisher.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
