
/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.journal.domain.jpa.BookEntity;
import com.kumasi.journal.mock.tool.MockValues;

public class BookEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public BookEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public BookEntity createInstance( Integer id ) {
		BookEntity entity = new BookEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setIsbn( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setTitle( mockValues.nextString(75) ) ; // java.lang.String 
		entity.setSubtitle( mockValues.nextString(250) ) ; // java.lang.String 
		entity.setAbstractDescription( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setNumberPages( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setAuthor( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfPublisher( TODO ) ; // List<Publisher> 
		// setListOfCategory( TODO ) ; // List<Category> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<BookEntity> createList(int count) {
		List<BookEntity> list = new LinkedList<BookEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
