
/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.journal.domain.jpa.EntryEntity;
import com.kumasi.journal.mock.tool.MockValues;

public class EntryEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public EntryEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public EntryEntity createInstance( Integer identry ) {
		EntryEntity entity = new EntryEntity();
		// Init Primary Key fields
		entity.setIdentry( identry) ;
		// Init Data fields
		entity.setTitle( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setStoryDefinition( mockValues.nextString(2147483647) ) ; // java.lang.String 
		entity.setSuccessFactory( mockValues.nextString(16777215) ) ; // java.lang.String 
		entity.setDateCreated( mockValues.nextDate() ) ; // java.util.Date 
		entity.setDateModified( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setEntrytype( TODO ) ; // Entrytype 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<EntryEntity> createList(int count) {
		List<EntryEntity> list = new LinkedList<EntryEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
