
/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.journal.domain.jpa.EntrytypeEntity;
import com.kumasi.journal.mock.tool.MockValues;

public class EntrytypeEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public EntrytypeEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public EntrytypeEntity createInstance( Integer id ) {
		EntrytypeEntity entity = new EntrytypeEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setDescription( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfEntry( TODO ) ; // List<Entry> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<EntrytypeEntity> createList(int count) {
		List<EntrytypeEntity> list = new LinkedList<EntrytypeEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
