/*
 * Created on 24 Oct 2015 ( Time 23:20:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service.impl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.List;

import com.kumasi.journal.domain.Publisher;
import com.kumasi.journal.domain.jpa.PublisherEntity;
import java.util.List;
import com.kumasi.journal.business.service.mapping.PublisherServiceMapper;
import com.kumasi.journal.persistence.services.jpa.PublisherPersistenceJPA;
import com.kumasi.journal.test.PublisherFactoryForTest;
import com.kumasi.journal.test.PublisherEntityFactoryForTest;
import com.kumasi.journal.test.MockValues;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

/**
 * Test : Implementation of PublisherService
 */
@RunWith(MockitoJUnitRunner.class)
public class PublisherServiceImplTest {

	@InjectMocks
	private PublisherServiceImpl publisherService;
	@Mock
	private PublisherPersistenceJPA publisherPersistenceJPA;
	@Mock
	private PublisherServiceMapper publisherServiceMapper;
	
	private PublisherFactoryForTest publisherFactoryForTest = new PublisherFactoryForTest();

	private PublisherEntityFactoryForTest publisherEntityFactoryForTest = new PublisherEntityFactoryForTest();

	private MockValues mockValues = new MockValues();
	
	@Test
	public void findById() {
		// Given
		Integer id = mockValues.nextInteger();
		
		PublisherEntity publisherEntity = publisherPersistenceJPA.load(id);
		
		Publisher publisher = publisherFactoryForTest.newPublisher();
		when(publisherServiceMapper.mapPublisherEntityToPublisher(publisherEntity)).thenReturn(publisher);

		// When
		Publisher publisherFound = publisherService.findById(id);

		// Then
		assertEquals(publisher.getId(),publisherFound.getId());
	}

	@Test
	public void findAll() {
		// Given
		List<PublisherEntity> publisherEntitys = new ArrayList<PublisherEntity>();
		PublisherEntity publisherEntity1 = publisherEntityFactoryForTest.newPublisherEntity();
		publisherEntitys.add(publisherEntity1);
		PublisherEntity publisherEntity2 = publisherEntityFactoryForTest.newPublisherEntity();
		publisherEntitys.add(publisherEntity2);
		when(publisherPersistenceJPA.loadAll()).thenReturn(publisherEntitys);
		
		Publisher publisher1 = publisherFactoryForTest.newPublisher();
		when(publisherServiceMapper.mapPublisherEntityToPublisher(publisherEntity1)).thenReturn(publisher1);
		Publisher publisher2 = publisherFactoryForTest.newPublisher();
		when(publisherServiceMapper.mapPublisherEntityToPublisher(publisherEntity2)).thenReturn(publisher2);

		// When
		List<Publisher> publishersFounds = publisherService.findAll();

		// Then
		assertTrue(publisher1 == publishersFounds.get(0));
		assertTrue(publisher2 == publishersFounds.get(1));
	}

	@Test
	public void create() {
		// Given
		Publisher publisher = publisherFactoryForTest.newPublisher();

		PublisherEntity publisherEntity = publisherEntityFactoryForTest.newPublisherEntity();
		when(publisherPersistenceJPA.load(publisher.getId())).thenReturn(null);
		
		publisherEntity = new PublisherEntity();
		publisherServiceMapper.mapPublisherToPublisherEntity(publisher, publisherEntity);
		PublisherEntity publisherEntitySaved = publisherPersistenceJPA.save(publisherEntity);
		
		Publisher publisherSaved = publisherFactoryForTest.newPublisher();
		when(publisherServiceMapper.mapPublisherEntityToPublisher(publisherEntitySaved)).thenReturn(publisherSaved);

		// When
		Publisher publisherResult = publisherService.create(publisher);

		// Then
		assertTrue(publisherResult == publisherSaved);
	}

	@Test
	public void createKOExists() {
		// Given
		Publisher publisher = publisherFactoryForTest.newPublisher();

		PublisherEntity publisherEntity = publisherEntityFactoryForTest.newPublisherEntity();
		when(publisherPersistenceJPA.load(publisher.getId())).thenReturn(publisherEntity);

		// When
		Exception exception = null;
		try {
			publisherService.create(publisher);
		} catch(Exception e) {
			exception = e;
		}

		// Then
		assertTrue(exception instanceof IllegalStateException);
		assertEquals("already.exists", exception.getMessage());
	}

	@Test
	public void update() {
		// Given
		Publisher publisher = publisherFactoryForTest.newPublisher();

		PublisherEntity publisherEntity = publisherEntityFactoryForTest.newPublisherEntity();
		when(publisherPersistenceJPA.load(publisher.getId())).thenReturn(publisherEntity);
		
		PublisherEntity publisherEntitySaved = publisherEntityFactoryForTest.newPublisherEntity();
		when(publisherPersistenceJPA.save(publisherEntity)).thenReturn(publisherEntitySaved);
		
		Publisher publisherSaved = publisherFactoryForTest.newPublisher();
		when(publisherServiceMapper.mapPublisherEntityToPublisher(publisherEntitySaved)).thenReturn(publisherSaved);

		// When
		Publisher publisherResult = publisherService.update(publisher);

		// Then
		verify(publisherServiceMapper).mapPublisherToPublisherEntity(publisher, publisherEntity);
		assertTrue(publisherResult == publisherSaved);
	}

	@Test
	public void delete() {
		// Given
		Integer id = mockValues.nextInteger();

		// When
		publisherService.delete(id);

		// Then
		verify(publisherPersistenceJPA).delete(id);
		
	}

}
