/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.kumasi.journal.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.kumasi.journal.domain.jpa.BookCategoryEntity;
import com.kumasi.journal.domain.jpa.BookCategoryEntityKey;
import com.kumasi.journal.persistence.commons.jpa.GenericJpaService;
import com.kumasi.journal.persistence.commons.jpa.JpaOperation;
import com.kumasi.journal.persistence.services.BookCategoryPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "BookCategory" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookCategoryPersistenceJPA extends GenericJpaService<BookCategoryEntity, BookCategoryEntityKey> implements BookCategoryPersistence {

	/**
	 * Constructor
	 */
	public BookCategoryPersistenceJPA() {
		super(BookCategoryEntity.class);
	}

	@Override
	public BookCategoryEntity load( Integer bookId, Integer categoryId ) {
		// Build the composite key
		BookCategoryEntityKey key = new BookCategoryEntityKey( bookId, categoryId );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer bookId, Integer categoryId ) {
		// Build the composite key
		BookCategoryEntityKey key = new BookCategoryEntityKey( bookId, categoryId );
		return super.delete( key );
	}

	@Override
	public boolean delete(BookCategoryEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			BookCategoryEntityKey key = new BookCategoryEntityKey( entity.getBookId(), entity.getCategoryId() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("BookCategoryEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
