/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.kumasi.journal.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.kumasi.journal.domain.jpa.BookPublisherEntity;
import com.kumasi.journal.domain.jpa.BookPublisherEntityKey;
import com.kumasi.journal.persistence.commons.jpa.GenericJpaService;
import com.kumasi.journal.persistence.commons.jpa.JpaOperation;
import com.kumasi.journal.persistence.services.BookPublisherPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "BookPublisher" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookPublisherPersistenceJPA extends GenericJpaService<BookPublisherEntity, BookPublisherEntityKey> implements BookPublisherPersistence {

	/**
	 * Constructor
	 */
	public BookPublisherPersistenceJPA() {
		super(BookPublisherEntity.class);
	}

	@Override
	public BookPublisherEntity load( Integer publisherId, Integer bookId ) {
		// Build the composite key
		BookPublisherEntityKey key = new BookPublisherEntityKey( publisherId, bookId );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer publisherId, Integer bookId ) {
		// Build the composite key
		BookPublisherEntityKey key = new BookPublisherEntityKey( publisherId, bookId );
		return super.delete( key );
	}

	@Override
	public boolean delete(BookPublisherEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			BookPublisherEntityKey key = new BookPublisherEntityKey( entity.getPublisherId(), entity.getBookId() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("BookPublisherEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
