/*
 * Created on 24 Oct 2015 ( Time 23:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.kumasi.journal.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.kumasi.journal.domain.jpa.EntrytypeEntity;
import com.kumasi.journal.persistence.commons.jpa.GenericJpaService;
import com.kumasi.journal.persistence.commons.jpa.JpaOperation;
import com.kumasi.journal.persistence.services.EntrytypePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Entrytype" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class EntrytypePersistenceJPA extends GenericJpaService<EntrytypeEntity, Integer> implements EntrytypePersistence {

	/**
	 * Constructor
	 */
	public EntrytypePersistenceJPA() {
		super(EntrytypeEntity.class);
	}

	@Override
	public EntrytypeEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(EntrytypeEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("EntrytypeEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
