/*
 * Created on 24 Oct 2015 ( Time 23:20:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.kumasi.journal.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.kumasi.journal.domain.jpa.PublisherEntity;
import com.kumasi.journal.persistence.commons.jpa.GenericJpaService;
import com.kumasi.journal.persistence.commons.jpa.JpaOperation;
import com.kumasi.journal.persistence.services.PublisherPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Publisher" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PublisherPersistenceJPA extends GenericJpaService<PublisherEntity, Integer> implements PublisherPersistence {

	/**
	 * Constructor
	 */
	public PublisherPersistenceJPA() {
		super(PublisherEntity.class);
	}

	@Override
	public PublisherEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(PublisherEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PublisherEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
