/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service;

import java.util.List;

import com.kumasi.journal.domain.Book;

/**
 * Business Service Interface for entity Book.
 */
public interface BookService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Book findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Book> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Book save(Book entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Book update(Book entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Book create(Book entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
