/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service;

import java.util.List;

import com.kumasi.journal.domain.BookPublisher;

/**
 * Business Service Interface for entity BookPublisher.
 */
public interface BookPublisherService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param publisherId
	 * @param bookId
	 * @return entity
	 */
	BookPublisher findById( Integer publisherId, Integer bookId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<BookPublisher> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	BookPublisher save(BookPublisher entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookPublisher update(BookPublisher entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookPublisher create(BookPublisher entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param publisherId
	 * @param bookId
	 */
	void delete( Integer publisherId, Integer bookId );


}
