/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service;

import java.util.List;

import com.kumasi.journal.domain.BookCategory;

/**
 * Business Service Interface for entity BookCategory.
 */
public interface BookCategoryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param bookId
	 * @param categoryId
	 * @return entity
	 */
	BookCategory findById( Integer bookId, Integer categoryId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<BookCategory> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	BookCategory save(BookCategory entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookCategory update(BookCategory entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookCategory create(BookCategory entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param bookId
	 * @param categoryId
	 */
	void delete( Integer bookId, Integer categoryId );


}
