/*
 * Created on 24 Oct 2015 ( Time 23:23:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.business.service;

import java.util.List;

import com.kumasi.journal.domain.Entrytype;

/**
 * Business Service Interface for entity Entrytype.
 */
public interface EntrytypeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Entrytype findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Entrytype> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Entrytype save(Entrytype entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Entrytype update(Entrytype entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Entrytype create(Entrytype entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
