/*
 * Created on 24 Oct 2015 ( Time 23:23:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.journal.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
